package com.hc.common.system;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName sys_menu
 */
@Data
public class SysMenu implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private Integer menuId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String menuName;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String menuUrl;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String parentId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String menuOrder;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String menuIcon;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private String menuType;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private Integer menuState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbg.generated 2021-04-08 14:19:57
     */
    private static final long serialVersionUID = 1L;
}