package com.hc.common.system;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName sys_role
 */
@Data
public class SysRole implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String roleId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String roleName;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String rights;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String parentId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String addQx;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String delQx;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String editQx;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String chaQx;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private String rnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated 2021-04-08 14:16:18
     */
    private static final long serialVersionUID = 1L;
}