package com.hc.common.system;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

/**
 * null
 * @TableName sys_user
 */
@Data
public class SysUser implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    @TableId
    private String userId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String rights;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String roleId;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String lastLogin;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String ip;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String status;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String bz;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String skin;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String email;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String number;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String phone;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String roleIds;

    /**
     * 微信用户ID
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String openid;

    /**
     * 微信头像
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String headPortrait;

    /**
     * 账无忧账号
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String kdzwyInterfaceCallAccount;

    /**
     * 账无忧密码
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String kdzwyInterfaceCallAccountPassword;

    /**
     * 账无忧accesstoken
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String kdzwyAccesstoken;

    /**
     * 
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated 2021-04-08 14:23:29
     */
    private static final long serialVersionUID = 1L;
}