server:
  port: 18001
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://localhost:3306/kbs-hc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:17001/eureka/